// <auto-generated />
using System;
using FIAP.AgroSolutions.Alerts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FIAP.AgroSolutions.Alerts.Infrastructure.Migrations
{
    [DbContext(typeof(AlertsDbContext))]
    partial class AlertsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FIAP.AgroSolutions.Alerts.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<DateTime>("TriggeredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FieldId", "Type", "TriggeredAtUtc");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("FIAP.AgroSolutions.Alerts.Domain.Entities.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CooldownMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Metric")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("Operator")
                        .HasColumnType("int");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal?>("SecondaryMaxValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("SecondaryMetric")
                        .HasColumnType("int");

                    b.Property<decimal?>("SecondaryMinValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<decimal>("ThresholdValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RuleKey")
                        .IsUnique();

                    b.ToTable("AlertRules", (string)null);
                });

            modelBuilder.Entity("FIAP.AgroSolutions.Alerts.Domain.Entities.FieldState", b =>
                {
                    b.Property<Guid>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("LastRainMm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastReadingAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LastSoilMoisturePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LastTemperatureC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("FieldId");

                    b.ToTable("FieldStates", (string)null);
                });

            modelBuilder.Entity("FIAP.AgroSolutions.Alerts.Domain.Entities.RuleState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AlertActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastTriggeredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WindowStartUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FieldId", "RuleKey")
                        .IsUnique();

                    b.ToTable("RuleStates", (string)null);
                });

            modelBuilder.Entity("FIAP.AgroSolutions.Alerts.Domain.Entities.SensorReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MeasuredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RainMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoilMoisturePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TemperatureC")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("FieldId", "MeasuredAtUtc");

                    b.ToTable("SensorReadings", (string)null);
                });

            modelBuilder.Entity("FIAP.AgroSolutions.Alerts.Domain.Entities.RuleState", b =>
                {
                    b.HasOne("FIAP.AgroSolutions.Alerts.Domain.Entities.FieldState", null)
                        .WithMany("Rules")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FIAP.AgroSolutions.Alerts.Domain.Entities.FieldState", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
